# Generated by Django 5.1.1 on 2024-09-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_alter_booking_flat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
