# Generated by Django 5.1.1 on 2024-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
