# Generated by Django 5.1.1 on 2024-09-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_alter_flat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flats.flat'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
