# Generated by Django 5.1.1 on 2024-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_alter_booking_flat_alter_flat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='previousId',
            field=models.IntegerField(default=1),
        ),
    ]
