# Generated by Django 5.1.1 on 2024-09-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_booking_previousid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='previousId',
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_bookings', to='flats.booking'),
        ),
    ]
