# Generated by Django 5.1.1 on 2024-09-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='previous_booking',
        ),
    ]
