# Generated by Django 5.1.1 on 2024-09-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0014_alter_flat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flats.flat'),
        ),
    ]
