# Generated by Django 5.1.1 on 2024-09-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0015_alter_booking_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
