# Generated by Django 5.1.1 on 2024-09-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0017_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
