# Generated by Django 5.1.1 on 2024-09-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0019_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='previous_booking',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
