# Generated by Django 5.1.1 on 2024-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0022_alter_booking_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(),
        ),
    ]
